apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: go-remote-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-remote-operator
  namespace: go-remote-operator
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: go-remote-operator-sa    
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
