apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: podconfig-operator
  name: cnf-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-remote
  namespace: cnf-test
  labels:
    app: go-remote
spec:
  selector:
    matchLabels:
      app: go-remote
  replicas: 1
  template:
    metadata:
      labels:
        app: go-remote
    spec:
      serviceAccountName: podconfig-operator-sa
      containers:
      # - command:
      #   - /manager
      #   args:
      #   - --enable-leader-election
      - name: go-remote      
        # image: linuxserver/openssh-server:latest
        # image: quay.io/acmenezes/c7-systemd:latest
        image: quay.io/acmenezes/go-remote:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 2222
          - containerPort: 2345
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /tmp/proc
            name: proc
          - mountPath: /var/run/crio/crio.sock
            name: crio-sock
          - mountPath: /etc/ssh/authorized_keys
            name: ssh-key
      volumes:
      - name: proc
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /proc
          type: Directory
      - name: crio-sock
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /var/run/crio/crio.sock
          type: Socket
      - name: ssh-key
        secret:
          secretName: secret-ssh-auth