
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-scc-privileged
  namespace: cnf-test
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-priv-scc-podconfig-operator
  namespace: cnf-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-scc-privileged
subjects:
  - kind: ServiceAccount
    name: podconfig-operator-sa
    namespace: cnf-test