apiVersion: v1
kind: Service
metadata:
  name: go-remote-svc
  labels:
    app: go-remote
spec:
  selector:
    app: go-remote
  ports:
  - name: ssh
    port: 2222
    targetPort: 2222
    protocol: TCP
  # - name: delve
  #   port: 2345
  #   targetPort: 2345
  #   protocol: TCP    
  type: LoadBalancer
