# permissions for end users to view goremotes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goremote-viewer-role
rules:
- apiGroups:
  - go-remote.opdev.io
  resources:
  - goremotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - go-remote.opdev.io
  resources:
  - goremotes/status
  verbs:
  - get
