# permissions for end users to edit goremotes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goremote-editor-role
rules:
- apiGroups:
  - go-remote.fennecproject.io
  resources:
  - goremotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-remote.fennecproject.io
  resources:
  - goremotes/status
  verbs:
  - get
