
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: go-remote-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - go-remote.fennecproject.io
  resources:
  - goremotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - go-remote.fennecproject.io
  resources:
  - goremotes/status
  verbs:
  - get
  - patch
  - update
