apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-remote-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-remote-manager-role
subjects:
- kind: ServiceAccount
  name: go-remote-operator-sa
  namespace: go-remote-operator
